"""Professional PDF meal report generation.

Reads the PERSISTED meal analysis (never recomputes any ML score) and
renders a multi-section PDF using ReportLab:

- Page 1: meal image, detected foods, nutrition summary
- Health analysis: DCI, NIS, disease probabilities, risk fusion
- AI Dietitian section (when present): health score, meal quality,
  summary, risk explanation, recommendations, alternatives, warnings
- Footer on every page: "Generated by DietRiskNet" + timestamp

Automatic page breaks are handled by ReportLab's platypus flowables.
"""

from __future__ import annotations

import html
import os
from backend.utils.datetime_utils import utcnow
from io import BytesIO
from typing import List, Optional

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from sqlalchemy.orm import Session

from backend.database.models import AIDietitianResult, Meal
from backend.utils.logger import app_logger


class ReportNotFoundError(Exception):
    """Raised when a meal does not exist or belongs to another user."""


# ---- palette -------------------------------------------------------------
_BRAND = colors.HexColor("#2563EB")
_TEXT = colors.HexColor("#111827")
_MUTED = colors.HexColor("#6B7280")
_ROW_ALT = colors.HexColor("#F3F4F6")
_HEADER_BG = colors.HexColor("#1F2937")

# ---- styles ---------------------------------------------------------------
_styles = getSampleStyleSheet()


def _p(name: str, **kw) -> ParagraphStyle:
    # Allow callers to override the parent via kw, falling back to BodyText.
    base = kw.pop("parent", _styles["BodyText"])
    return ParagraphStyle(name, parent=base, **kw)


ST_TITLE = _p("ReportTitle", fontName="Helvetica-Bold", fontSize=20,
              textColor=_BRAND, spaceAfter=2, alignment=TA_CENTER)
ST_SUBTITLE = _p("ReportSubtitle", fontSize=9, textColor=_MUTED,
                 alignment=TA_CENTER, spaceAfter=14)
ST_SECTION = _p("ReportSection", fontName="Helvetica-Bold", fontSize=13,
                textColor=_BRAND, spaceBefore=14, spaceAfter=6)
ST_BODY = _p("ReportBody", fontSize=10, textColor=_TEXT, leading=14)
ST_BODY_CENTER = _p("ReportBodyCenter", parent=ST_BODY, alignment=TA_CENTER)
ST_LABEL = _p("ReportLabel", fontName="Helvetica-Bold", fontSize=10,
              textColor=_TEXT)
ST_SMALL = _p("ReportSmall", fontSize=8, textColor=_MUTED)
ST_BULLET = _p("ReportBullet", fontSize=10, textColor=_TEXT, leading=14,
               leftIndent=14, bulletIndent=4, spaceAfter=2)
ST_IMAGE_NOTE = _p("ReportImageNote", fontSize=8, textColor=_MUTED,
                   alignment=TA_CENTER)


def _escape(value) -> str:
    return html.escape(str(value)) if value is not None else "—"


def _fmt(value, digits: int = 1) -> str:
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return "—"


class ReportService:
    """Renders a meal analysis into a downloadable PDF."""

    def generate_report(
        self,
        db: Session,
        *,
        user_id: int,
        meal_id: int,
    ) -> bytes:
        """Build the PDF for *meal_id* (owned by *user_id*).

        Returns raw PDF bytes.
        Raises ReportNotFoundError if the meal is missing / not owned.
        """
        meal = db.query(Meal).filter(Meal.id == meal_id).first()
        if meal is None or meal.user_id != user_id:
            raise ReportNotFoundError(
                "Meal not found for the current user."
            )

        ai_row = (
            db.query(AIDietitianResult)
            .filter(AIDietitianResult.meal_id == meal_id)
            .order_by(AIDietitianResult.created_at.desc())
            .first()
        )

        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            leftMargin=0.75 * inch,
            rightMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.9 * inch,
            title=f"DietRiskNet Meal Report {meal_id}",
            author="DietRiskNet",
        )

        timestamp = utcnow().strftime("%Y-%m-%d %H:%M UTC")

        def _footer(canvas, _doc):
            canvas.saveState()
            canvas.setFont("Helvetica", 8)
            canvas.setFillColor(_MUTED)
            canvas.drawCentredString(A4[0] / 2, 0.5 * inch, "Generated by DietRiskNet")
            canvas.drawRightString(
                A4[0] - 0.75 * inch, 0.5 * inch, timestamp
            )
            canvas.restoreState()

        story: List = self._build_story(meal, ai_row)
        doc.build(story, onFirstPage=_footer, onLaterPages=_footer)

        return buffer.getvalue()

    # ------------------------------------------------------------------
    # Story builders
    # ------------------------------------------------------------------

    def _build_story(self, meal: Meal, ai_row: Optional[AIDietitianResult]) -> List:
        story: List = []

        # Title
        story.append(Paragraph("DietRiskNet — Meal Analysis Report", ST_TITLE))
        story.append(Paragraph(
            f"Meal ID: {meal.id} &nbsp;|&nbsp; "
            f"Logged: {meal.created_at.strftime('%Y-%m-%d %H:%M') if meal.created_at else '—'}",
            ST_SUBTITLE,
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=_BRAND, spaceAfter=10))

        # Meal image
        story.append(Paragraph("1. Meal Snapshot", ST_SECTION))
        story.extend(self._meal_image_flowables(meal))

        # Detected foods
        story.append(Paragraph("Detected Foods", ST_SECTION))
        story.extend(self._foods_table(meal))

        # Nutrition summary
        story.append(Paragraph("Nutrition Summary", ST_SECTION))
        story.extend(self._nutrition_table(meal))

        # Health analysis
        story.append(Paragraph("Health Analysis", ST_SECTION))
        story.extend(self._health_analysis(meal))

        # AI Dietitian
        if ai_row is not None:
            story.append(Paragraph("AI Dietitian", ST_SECTION))
            story.extend(self._ai_section(ai_row))

        story.append(Spacer(1, 16))
        story.append(HRFlowable(width="100%", thickness=0.5, color=_MUTED))
        story.append(Spacer(1, 4))
        story.append(Paragraph(
            "This report is generated automatically from a meal analysis and is "
            "not a substitute for professional medical advice.", ST_SMALL,
        ))

        return story

    # ------------------------------------------------------------------
    def _meal_image_flowables(self, meal: Meal) -> List:
        flowables: List = []
        path = getattr(meal, "image_path", None)
        if path and os.path.exists(path):
            try:
                flowables.append(Image(
                    path,
                    width=4.5 * inch,
                    height=3.0 * inch,
                ))
                flowables.append(Spacer(1, 8))
            except Exception as exc:
                app_logger.warning(
                    "Report image skipped (%s): %s", path, exc
                )
                flowables.append(Paragraph(
                    "Meal image could not be embedded.", ST_IMAGE_NOTE
                ))
                flowables.append(Spacer(1, 6))
        else:
            flowables.append(Paragraph(
                "Meal image not available.", ST_IMAGE_NOTE
            ))
            flowables.append(Spacer(1, 6))
        return flowables

    def _foods_table(self, meal: Meal) -> List:
        header = ["#", "Food", "Weight (g)", "Calories", "Protein (g)", "Carbs (g)", "Fats (g)"]
        rows = [header]
        for idx, item in enumerate(meal.items, start=1):
            rows.append([
                str(idx),
                _escape(item.name),
                _fmt(item.weight_g, 0),
                _fmt(item.calories, 0),
                _fmt(item.protein, 1),
                _fmt(item.carbs, 1),
                _fmt(item.fats, 1),
            ])

        if len(rows) == 1:
            rows.append(["—", "No food items recorded", "", "", "", "", ""])

        table = Table(rows, repeatRows=1, colWidths=[0.4*inch, 2.2*inch, 0.9*inch, 0.8*inch, 0.8*inch, 0.8*inch, 0.8*inch])
        table.setStyle(self._table_style(len(rows)))
        return [table, Spacer(1, 8)]

    def _nutrition_table(self, meal: Meal) -> List:
        n = meal.nutrition
        nutrients = [
            ("Calories (kcal)", _fmt(n.calories, 0) if n else "—"),
            ("Protein (g)", _fmt(n.protein, 1) if n else "—"),
            ("Carbohydrates (g)", _fmt(n.carbs, 1) if n else "—"),
            ("Fat (g)", _fmt(n.fats, 1) if n else "—"),
            ("Fiber (g)", _fmt(n.fiber, 1) if n else "—"),
            ("Sugar (g)", _fmt(n.sugar, 1) if n else "—"),
            ("Sodium (mg)", _fmt(n.sodium, 0) if n else "—"),
        ]
        # Two-column layout: label / value pairs in a 2xN table.
        half = (len(nutrients) + 1) // 2
        left = nutrients[:half]
        right = nutrients[half:]
        rows = []
        for i in range(max(len(left), len(right))):
            a = left[i] if i < len(left) else ("", "")
            b = right[i] if i < len(right) else ("", "")
            rows.append([a[0], a[1], b[0], b[1]])

        table = Table(rows, colWidths=[1.6*inch, 1.1*inch, 1.6*inch, 1.1*inch])
        style = [
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TEXTCOLOR", (0, 0), (-1, -1), _TEXT),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, _ROW_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
        table.setStyle(TableStyle(style))
        return [table, Spacer(1, 8)]

    def _health_analysis(self, meal: Meal) -> List:
        flowables: List = []

        p = meal.predictions
        fusion = meal.fusion_result

        # DCI / NIS
        dci_label = _escape(meal.dci_level or "—")
        nis_label = _escape(meal.nis_level or "—")
        flowables.append(Paragraph(
            f"Dietary Consistency Index (DCI): "
            f"<b>{_fmt(meal.dci, 4)}</b> ({dci_label})",
            ST_BODY,
        ))
        flowables.append(Paragraph(
            f"Nutritional Imbalance Score (NIS): "
            f"<b>{_fmt(meal.nis, 4)}</b> ({nis_label})",
            ST_BODY,
        ))
        flowables.append(Spacer(1, 6))

        # Disease probabilities
        risks = [
            ("Diabetes", p.diabetes_risk if p else None),
            ("Obesity", p.obesity_risk if p else None),
            ("Hypertension", p.hypertension_risk if p else None),
            ("Nutritional Deficiency", p.deficiency_risk if p else None),
        ]
        rows = [["Condition", "Risk Probability"]]
        for name, value in risks:
            rows.append([name, _fmt(value * 100, 1) + " %" if value is not None else "—"])
        table = Table(rows, colWidths=[2.2*inch, 1.4*inch])
        table.setStyle(self._table_style(len(rows)))
        flowables.append(table)
        flowables.append(Spacer(1, 6))

        # Risk fusion
        fused_score = fusion.fused_score if fusion else None
        fused_level = _escape(fusion.risk_level if fusion else "—")
        flowables.append(Paragraph(
            f"Risk Fusion Score: <b>{_fmt(fused_score * 100, 1)} %</b> "
            f"({fused_level})",
            ST_BODY,
        ))

        return flowables

    def _ai_section(self, ai: AIDietitianResult) -> List:
        flowables: List = []

        score = _escape(ai.health_score if ai.health_score is not None else "—")
        level = _escape(ai.health_level or "—")
        quality = _escape(ai.meal_quality or "—")

        flowables.append(Paragraph(
            f"Health Score: <b>{score} / 100</b> &nbsp;({level})", ST_BODY,
        ))
        flowables.append(Paragraph(f"Meal Quality: <b>{quality}</b>", ST_BODY))
        flowables.append(Spacer(1, 6))

        if ai.summary:
            flowables.append(Paragraph("AI Summary", ST_LABEL))
            flowables.append(Paragraph(_escape(ai.summary), ST_BODY))
            flowables.append(Spacer(1, 6))

        if ai.risk_explanation:
            flowables.append(Paragraph("Risk Explanation", ST_LABEL))
            flowables.append(Paragraph(_escape(ai.risk_explanation), ST_BODY))
            flowables.append(Spacer(1, 6))

        for title, values in (
            ("Recommendations", ai.recommendations_json or []),
            ("Healthier Alternatives", ai.alternatives_json or []),
            ("Warnings", ai.warnings_json or []),
        ):
            if not values:
                continue
            flowables.append(Paragraph(title, ST_LABEL))
            for value in values:
                flowables.append(Paragraph(
                    _escape(value), ST_BULLET, bulletText="•",
                ))
            flowables.append(Spacer(1, 4))

        return flowables

    # ------------------------------------------------------------------
    @staticmethod
    def _table_style(num_rows: int) -> TableStyle:
        style = [
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, 0), (-1, 0), _HEADER_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _ROW_ALT]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ]
        return TableStyle(style)


# Singleton for convenience (matches the project's service pattern).
report_service = ReportService()
